databases:
  - name: blog
    databaseName: blog_production
    user: blog
    plan: free

services:
  - type: web
    name: blog
    runtime: docker
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: blog
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: RAILS_ENV
        value: production
      - key: WEB_CONCURRENCY
        value: 2 # sensible default
    buildCommand: bundle install && bundle exec rake db:migrate
    startCommand: |
      bundle exec rake db:seed
      bundle exec puma -C config/puma.rb
